"""empty message

Revision ID: 613f2a2aee32
Revises: a5cffa318ac2
Create Date: 2024-09-21 10:02:37.865213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613f2a2aee32'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_personaje', sa.String(length=250), nullable=False),
    sa.Column('peliculas_personaje', sa.String(length=250), nullable=False),
    sa.Column('raza_personaje', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_planeta', sa.String(length=250), nullable=False),
    sa.Column('ubicacion_planeta', sa.String(length=250), nullable=False),
    sa.Column('habitantes_planeta', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personajes_favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personaje_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personaje_id'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planetas_favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planeta_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planeta_id'], ['planetas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    op.drop_table('planetas_favoritos')
    op.drop_table('personajes_favoritos')
    op.drop_table('planetas')
    op.drop_table('personajes')
    # ### end Alembic commands ###
